**
!autoware_carla_launch/
!autoware_carla_launch/**
!autoware_overlay/
!autoware_overlay/**
!unicarla_ads/
!unicarla_ads/**

# 数据、构建产物与 git 元数据不打进上下文
autoware_carla_launch/autoware_data
autoware_carla_launch/autoware_data/**
autoware_carla_launch/carla_map
autoware_carla_launch/carla_map/**
autoware_carla_launch/build
autoware_carla_launch/build/**
autoware_carla_launch/install
autoware_carla_launch/install/**
autoware_carla_launch/log
autoware_carla_launch/log/**
autoware_carla_launch/**/target
autoware_carla_launch/**/target/**
autoware_carla_launch/**/.git
autoware_carla_launch/**/__pycache__
autoware_carla_launch/**/__pycache__/**
autoware_carla_launch/**/.venv
autoware_carla_launch/**/.venv/**
unicarla_ads/**/__pycache__
unicarla_ads/**/__pycache__/**
